### ISSUE TITLE
Sequel models do not work with custom serializers

### ISSUE THREAD

**Issue by azhi** [nesaulov/surrealist#83]
Minimal reproduction:

```ruby
require 'sequel'
require 'surrealist'

FileUtils.rm('test.sqlite') if File.exists?('test.sqlite')
DB = Sequel.sqlite('test.sqlite')
DB.create_table('users') do
  primary_key :id
  String :name
end

class UserSerializer < Surrealist::Serializer
  json_schema {
    {id: Integer, name: String}
  }
end

class User < Sequel::Model
  include Surrealist

  surrealize_with UserSerializer
end

User.create(name: 'Name')

User.first.surrealize
UserSerializer.new(User.first).surrealize
```

Last two lines both failing with:

```
Traceback (most recent call last):
	3: from test.rb:25:in `<main>'
	2: from .../gems/surrealist-35c87f58b098/lib/surrealist/instance_methods.rb:55:in `surrealize'
	1: from .../gems/surrealist-35c87f58b098/lib/surrealist/serializer.rb:45:in `surrealize'
.../gems/surrealist-35c87f58b098/lib/surrealist.rb:59:in `surrealize_collection': undefined method `map' for #<User @values={:id=>1, :name=>"Name"}> (NoMethodError)
Did you mean?  tap
```

The cause is [here](https://github.com/nesaulov/surrealist/blob/35c87f58b098/lib/surrealist/serializer.rb#L44). Same check is performed in some other places in source code.

**Comment by nesaulov** [comment]
Yes, you are right, thank you for the issue and PR! We need to make sure this applies to all orms and edit the error message.
